quarkus.langchain4j.ai.gemini.api-key=AIzaSyD0dAz5BpLYK676MEGhkMd5YJYT3m3-0co
quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true
quarkus.langchain4j.ai.gemini.chat-model.model-id=gemini-2.5-flash
quarkus.langchain4j.ai.gemini.chat-model.temperature=0.5
quarkus.langchain4j.ai.gemini.embedding-model.model-id=text-embedding-001
quarkus.langchain4j.chat-memory.memory-window.max-messages=20
quarkus.langchain4j.chat-memory.type=MESSAGE_WINDOW